#!/bin/sh
# Generate no$gmb compatible .sym file based on new banked .noi file

# set in and out to correct values
in=$1
out=$2
if [ "$#" -eq 1 ]; then
    out=$(basename ${in} .noi).sym
else
    if [ ! $# -eq 2 ]; then
        echo $0 in.noi [out.sym]
        exit 1
    fi
fi

echo "; no\$gmb compatible .sym file" > ${out}
echo "; Generated by noi2sym.sh" >> ${out}

# filter rows and change format
awk '($1=="DEF" && substr($2, 0, 2) != "b_" && $2 != ".__.ABS." && substr($2, 0, 3) != "l__" && (substr($2, 0, 3) != "s__" || $2 == "s__HEAP" || $2 == "s__BSS")){\
       $3=strtonum($3);\
       printf "%02X:%04X %s\n", rshift($3, 16), and($3,0xFFFF), $2\
     }' ${in} >> ${out}